CREATE TABLE IF NOT EXISTS care_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER REFERENCES patient_cases(id) ON DELETE CASCADE,
    plan_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    payload_json TEXT NOT NULL,
    created_by TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE INDEX IF NOT EXISTS idx_care_plans_case
ON care_plans(case_id, created_at DESC);

CREATE TABLE IF NOT EXISTS note_drafts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER REFERENCES patient_cases(id) ON DELETE CASCADE,
    note_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_by TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE INDEX IF NOT EXISTS idx_note_drafts_case
ON note_drafts(case_id, created_at DESC);
